import prisma from "@/lib/db/prisma";
import type { Prisma } from "@/lib/generated/prisma/client";

// imcrm: snapshot of real blanka `document_types` rows for car (quote_type_id: 1), so local
// dev has realistic data instead of placeholders. Extend with health/home/etc. snapshots as
// they're pulled from blanka. IDs are the real blanka ids, kept explicit for eventual parity
// testing against the Laravel API — the sequence realignment below must run after seeding.
const rows: Prisma.DocumentTypeCreateInput[] = [
  {
    id: BigInt(203),
    code: "OTHERS_CAR",
    text: "Other documents",
    description: "Please provide any other relevant documents and pictures of the incident, if available.",
    isActive: true,
    quoteType: { connect: { id: 1 } },
    folderPath: "car",
    acceptedFiles: ".pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png",
    maxFiles: 10,
    maxSize: 25,
    isRequired: false,
    sendToCustomer: false,
    sortOrder: 4,
    receiveFromCustomer: true,
    category: "QUOTE",
    isRequiredForSendPolicy: false,
  },
  {
    id: BigInt(156),
    code: "CAR_MULKIY",
    text: "Vehicle license (Mulkiya) or Dealer invoice copy or VCC (Front & Back)",
    description:
      "Please upload clear document or picture. If buying a brand new car, please upload the dealer invoice or vehicle clearance certificate.",
    isActive: true,
    quoteType: { connect: { id: 1 } },
    folderPath: "car",
    acceptedFiles: ".pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png",
    maxFiles: 2,
    maxSize: 25,
    isRequired: true,
    sendToCustomer: false,
    sortOrder: 2,
    receiveFromCustomer: true,
    category: "QUOTE",
    isRequiredForSendPolicy: false,
    toolTip: "Upload your Mulkiya showing plate number and car details.",
  },
  {
    id: BigInt(142),
    code: "VCP",
    text: "Vehicle photos (as per format shared by the advisor)",
    description: "",
    isActive: false,
    quoteType: { connect: { id: 1 } },
    folderPath: "car",
    acceptedFiles: ".jpeg,.jpg,.png",
    maxFiles: 20,
    maxSize: 25,
    isRequired: false,
    sendToCustomer: false,
    sortOrder: 62,
    receiveFromCustomer: true,
    category: "ISSUING_DOCUMENTS",
    isRequiredForSendPolicy: false,
  },
  {
    id: BigInt(129),
    code: "CPS",
    text: "Policy Schedule",
    description: "",
    isActive: true,
    quoteType: { connect: { id: 1 } },
    folderPath: "car",
    acceptedFiles: ".pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png",
    maxFiles: 5,
    maxSize: 2,
    isRequired: true,
    sendToCustomer: true,
    sortOrder: 11,
    receiveFromCustomer: false,
    category: "ISSUING_DOCUMENTS",
    isRequiredForSendPolicy: true,
  },
  {
    id: BigInt(118),
    code: "CPC",
    text: "Policy Certificate",
    description: "",
    isActive: true,
    quoteType: { connect: { id: 1 } },
    folderPath: "car",
    acceptedFiles: ".pdf,.xlsx,.xls,.docx,.doc,.jpeg,.jpg,.png",
    maxFiles: 5,
    maxSize: 2,
    isRequired: true,
    sendToCustomer: true,
    sortOrder: 12,
    receiveFromCustomer: false,
    category: "ISSUING_DOCUMENTS",
    isRequiredForSendPolicy: true,
  },
  {
    id: BigInt(20),
    code: "PHB",
    text: "Policy Handbook",
    isActive: true,
    quoteType: { connect: { id: 1 } },
    folderPath: "car",
    acceptedFiles: ".pdf,.xlsx,.docx,.jpeg,.jpg,.png",
    maxFiles: 5,
    maxSize: 25,
    isRequired: false,
    sendToCustomer: true,
    receiveFromCustomer: false,
    category: "QUOTE",
    isRequiredForSendPolicy: true,
  },
  {
    id: BigInt(17),
    code: "DL",
    text: "Driver's license (Front & Back)",
    description: "Please upload your valid UAE Driver's license.",
    isActive: true,
    quoteType: { connect: { id: 1 } },
    folderPath: "car",
    acceptedFiles: ".pdf,.xlsx,.docx,.jpeg,.jpg,.png",
    maxFiles: 2,
    maxSize: 25,
    isRequired: true,
    sendToCustomer: false,
    sortOrder: 1,
    receiveFromCustomer: true,
    category: "QUOTE",
    isRequiredForSendPolicy: false,
    toolTip: "Upload the front and back of your valid UAE driving license showing the license number.",
  },
  {
    id: BigInt(4),
    code: "CEID",
    text: "Emirates ID (Front & Back)",
    description: "Please upload your valid Emirates ID.",
    isActive: true,
    quoteType: { connect: { id: 1 } },
    folderPath: "car",
    acceptedFiles: ".pdf,.xlsx,.docx,.jpeg,.jpg,.png",
    maxFiles: 2,
    maxSize: 20,
    isRequired: true,
    sendToCustomer: false,
    sortOrder: 3,
    receiveFromCustomer: true,
    category: "QUOTE",
    isRequiredForSendPolicy: false,
    toolTip: "Upload both sides of your Emirates ID with the residence ID number visible.",
  },
];

export async function seedDocumentTypes() {
  for (const data of rows) {
    await prisma.documentType.upsert({
      where: { code: data.code },
      create: data,
      update: data,
    });
  }

  await prisma.$executeRawUnsafe(`
    SELECT setval(
      pg_get_serial_sequence('"DocumentType"', 'id'),
      COALESCE((SELECT MAX(id) FROM "DocumentType"), 1)
    );
  `);

  console.log(`imcrm: seeded ${rows.length} document_types rows`);
}
